### ISSUE TITLE
Add documentation for packing electron app on Linux

### ISSUE THREAD

**Issue by sunglocto** [SpecifiesDev/snapchat-electron#3]
Hey there.
I suggest adding documentation for packaging the app on Linux, as it's almost completely identical to packaging it to windows. You just have to change 
`electron-packager . snapchat-electron-port --overwrite --platform=**win32** --icon=<PATH_TO_ICON>`
to
`electron-packager . snapchat-electron-port --overwrite --platform=**linux** --icon=<PATH_TO_ICON>`
This creates an executable called "snapchat-electron-port".
So far, I have seen no issues with using this.

**Comment by cs-dad** [comment]
The command has been properly updated in the README file. Thanks for the suggestion.
