### ISSUE TITLE
All releases missing?

### ISSUE THREAD

**Issue by agottschling** [SpecifiesDev/snapchat-electron#4]
Went to download and noticed that there are no released listed. Is this app no longer supported?

**Comment by cs-dad** [comment]
Hello! When I released the program I actually had removed the releases for a while and forgot to put them back on the repository. I went ahead and compiled the source into a release for you. It's windows based.

But yes, this project is no longer supported. If you have an amazing idea that is implementable with the engine, I'd love to add it, but I pretty much got it to the place I wanted it to be. If you ever want to compile on your own source, or just recompile for whatever reason refer to the README for detailed instructions.

**Comment by agottschling** [comment]
Hey! Thanks for posting that and for the update. If I do think of any features I'll be sure to post enhancements or PRs.
Cheers!
